#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <pthread.h>
#include "proto.h"
#include "server.h"

// Global variables
int server_sockfd = 0, client_sockfd = 0;
ClientList *root, *now;

//used by signal function
//when signal interrupt occur use this function to close all socket
void catch_ctrl_c_and_exit(int sig) {
    ClientList *tmp;
    while (root != NULL) {
        printf("\nClose socketfd: %d\n", root->data);
        close(root->data); // close all socket include server_sockfd
        tmp = root;
        root = root->link;//point to next Clientnode
        free(tmp);
    }
    printf("Bye\n");
    exit(EXIT_SUCCESS);
}

//use this function to send the message to all the client 
void send_to_all_clients(ClientList *np, char tmp_buffer[]) {
    ClientList *tmp = root->link;
    while (tmp != NULL) {
        if (np->data != tmp->data) { // all clients except itself.
            printf("Send to sockfd %d: \"%s\" \n", tmp->data, tmp_buffer);
            //tmp_buffer is the message 
            //LENGTH_SEND is the length of message
            //tmp->data is the socket created before
            send(tmp->data, tmp_buffer, LENGTH_SEND, 0);
        }
        tmp = tmp->link;
    }
}
//to deal with the connection
void client_handler(void *p_client) {
    int leave_flag = 0;
    char nickname[LENGTH_NAME] = {};
    char recv_buffer[LENGTH_MSG] = {};
    char send_buffer[LENGTH_SEND] = {};
    //create a client node
    ClientList *np = (ClientList *)p_client;

    // Naming
    //recv() is used to receive message from socket
    //if nickname length exceed the range it will ask the client to enter again
    //if tthe format is correct it will print the information of client's neckname
    if (recv(np->data, nickname, LENGTH_NAME, 0) <= 0 || strlen(nickname) < 2 || strlen(nickname) >= LENGTH_NAME-1) {
        printf("%s didn't input name.\n", np->ip);
        leave_flag = 1;
    } else {
        strncpy(np->name, nickname, LENGTH_NAME);
        printf("%s(%s)(%d) join the chatroom.\n", np->name, np->ip, np->data);
        sprintf(send_buffer, "%s(%s) join the chatroom.", np->name, np->ip);
        send_to_all_clients(np, send_buffer);
    }

    // Conversation
    while (1) {
        if (leave_flag) {
            break;
        }
        int receive = recv(np->data, recv_buffer, LENGTH_MSG, 0);
        //receive will return the length of message on successful completion
        //if recv_buffer length is 0 means there didn't contain any message need to be sended
        //if it contain the message in recv_buffer then it will cope it to send_buffer
        //if client enter exit then the his connection will be suspend
        //if receive smaller than 0 means it didn't complete successfully
        if (receive > 0) {
            if (strlen(recv_buffer) == 0) {
                continue;
            }
            sprintf(send_buffer, "%s：%s from %s", np->name, recv_buffer, np->ip);
        } else if (receive == 0 || strcmp(recv_buffer, "exit") == 0) {
            printf("%s(%s)(%d) leave the chatroom.\n", np->name, np->ip, np->data);
            sprintf(send_buffer, "%s(%s) leave the chatroom.", np->name, np->ip);
            leave_flag = 1;
        } else {
            printf("Fatal Error: -1\n");
            leave_flag = 1;
        }
        //use the send_to_all_clients to send the message to all client
        send_to_all_clients(np, send_buffer);
    }

    // Remove Node
    close(np->data);
    if (np == now) { // remove an edge node
        now = np->prev;
        now->link = NULL;
    } else { // remove a middle node
        //break the remove node's link from previous node and next node 
        np->prev->link = np->link;
        np->link->prev = np->prev;
    }
    free(np);
}

int main()
{
    //SIGINT(Signal Interrupt) Interactive attention signal. Generally generated by the application user
    //catch_ctrl_c_and_exist is self define function
    signal(SIGINT, catch_ctrl_c_and_exit);

    // Create socket use the domain with IPv4 internet protocol version 4 
    //type SOCK_STREAM provide double-sided  Transmission Control Protocol
    //protocol 0 will use the preset mode which is dependent on domain and type
    //return a file descriptor for new socket if success,return -1 if fail
    server_sockfd = socket(AF_INET , SOCK_STREAM , 0);
    //fail to create socket (exit)
    if (server_sockfd == -1) {
        printf("Fail to create a socket.");
        exit(EXIT_FAILURE);
    }

    // Socket information
    struct sockaddr_in server_info, client_info;
    int s_addrlen = sizeof(server_info);
    int c_addrlen = sizeof(client_info);
    //clean memory fill it with 0
    memset(&server_info, 0, s_addrlen);
    memset(&client_info, 0, c_addrlen);
    server_info.sin_family = PF_INET;//Given a socket name
    server_info.sin_addr.s_addr = INADDR_ANY;//Given the host address
    server_info.sin_port = htons(8888);//Given a port number

    // Bind and Listen
    //sever_socket is the socket created above
    //use bind to link the IP address with sever 
    //use listen to wait for the request from client
    bind(server_sockfd, (struct sockaddr *)&server_info, s_addrlen);
    listen(server_sockfd, 5);

    // Print Server IP
    // use getsockname to get the information of IP and port
    getsockname(server_sockfd, (struct sockaddr*) &server_info, (socklen_t*) &s_addrlen);
    printf("Start Server on: %s:%d\n", inet_ntoa(server_info.sin_addr), ntohs(server_info.sin_port));

    // Initial linked list for clients
    //inet_nota is to convert the internet binary number (sever_info.sin_addr) into address
    root = newNode(server_sockfd, inet_ntoa(server_info.sin_addr));
    now = root;

    while (1) {
        //after bind and listen when there have the connection it will handle it  and return a new socket to cope with next connection
        //if connection success the structure &client_info point to will add into host information 
        client_sockfd = accept(server_sockfd, (struct sockaddr*) &client_info, (socklen_t*) &c_addrlen);

        // Print Client IP
        //getpeername return the address and port of the client
        //inet_ntoa transfer address to string with "."
        //ntohs is used to convert number between network byte order and the order of powerpc
        getpeername(client_sockfd, (struct sockaddr*) &client_info, (socklen_t*) &c_addrlen);
        printf("Client %s:%d come in.\n", inet_ntoa(client_info.sin_addr), ntohs(client_info.sin_port));

        // Append linked list for clients
        ClientList *c = newNode(client_sockfd, inet_ntoa(client_info.sin_addr));
        //point the new node's prev to now then now's link point to new node
        //make the new client node become now node
        c->prev = now;
        now->link = c;
        now = c;

        //create pthread to handle the connection
        pthread_t id;
        //client_handler is the self definr function
        //if pthread create successfully then it will handle the sending task
        //if pthread create unsuccessfully then it will print the erro message then exit
        if (pthread_create(&id, NULL, (void *)client_handler, (void *)c) != 0) {
            perror("Create pthread error!\n");
            exit(EXIT_FAILURE);
        }
    }

    return 0;
}
